# Generated by Django 5.2.7 on 2025-11-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Введите заголовок",
                        max_length=150,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Введите заголовок", verbose_name="Содержание"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Загрузите изображение",
                        upload_to="blog/photo",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "date_of_creation",
                    models.DateField(default=0, verbose_name="Счётчик просмотров"),
                ),
                ("publication_sign", models.BooleanField(default=True)),
                ("views_counter", models.PositiveIntegerField()),
            ],
        ),
    ]
