# Generated by Django 5.2.7 on 2025-12-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={"verbose_name": "blog", "verbose_name_plural": "blogs"},
        ),
        migrations.AlterField(
            model_name="blog",
            name="content",
            field=models.TextField(
                help_text="Введите Содержание", verbose_name="Содержание"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="date_of_creation",
            field=models.DateField(
                blank=True, default=0, null=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="views_counter",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Счётчик просмотров"
            ),
        ),
    ]
