# Generated by Django 5.2.7 on 2025-11-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(blank=True, null=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                upload_to="product/photo", verbose_name="Фотография"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.CharField(max_length=150, verbose_name="Цена за покупку"),
        ),
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
